# Generated by Django 3.1.7 on 2021-03-02 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
