# Generated by Django 3.1.5 on 2021-04-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0003_auto_20210408_1232'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inventoryrecords',
            index=models.Index(fields=['seller', 'transaction_type'], name='inventories_seller__320b8e_idx'),
        ),
    ]
