# Generated by Django 3.1.7 on 2021-02-28 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('inventory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_amount', to='inventories.inventory')),
            ],
        ),
    ]
